### ISSUE TITLE
Tokenization problem

### ISSUE THREAD

**Issue by frayalisia** [frayalisia/novelgraphs#1]
- [x]  @envypole, решить проблему с токенизацией

Как видишь, тут проблема с тем, что кавычка приклеилась к слову, из-за чего возникают трудности с разметкой прямой речи.

| Index | SentenceID | TokenID | Token | Lemma | Pos | NER | DepParse |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 68 | 0 | 68 | ' | ' | '' | O | 60 |
| 69 | 0 | 69 | thought | think | VBD | O | 59 |
| 70 | 0 | 70 | Alice | Alice | NNP | O | 72 |
| 71 | 0 | 71 | **'without** | 'without | NNP | O | 72 |
| 72 | 0 | 72 | pictures | picture | NNS | O | 69 |
| 73 | 0 | 73 | or | or | CC | O | 72 |
| 74 | 0 | 74 | conversation | conversation | NN | O | 72 |
| 75 | 0 | 75 | ? | ? | . | O | 30 |
| 76 | 0 | 76 | ' | ' | '' | O | 30 |

**Comment by PavelNovichkov** [comment]
Possible solutions:
- use CoreNLP tokenizer #2 
- use CoreNLP quote annotator #3

**Comment by PavelNovichkov** [comment]
CoreNLP tokenizer solves the problem
