### ISSUE TITLE
Double rows

### ISSUE THREAD

**Issue by frayalisia** [frayalisia/novelgraphs#10]
In the table it looks like this:

| SentenceID | TokenID | Token | Lemma | Pos | NER | DepParse | DepRel | Dialog |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 33454 | 2170 | 9 | , | , | , | O | 8 | punct |
| 33455 | 2170 | 10 | too | too | RB | O | 8 | advmod |
| 33456 | 2170 | 11 | . | . | . | O | 6 | punct |
| 33457 | 1254 | 12 | **NaN** | girl | NN | O | 9 | dobj |
| 33458 | 1254 | 13 | **NaN** | . | . | O | 3 | punct |

Possible solution: _table.dropna(how='any')_

Texts with the same problem:
- Breakfast at Tiffany's
- Solaris
- Brave New World

**Comment by frayalisia** [comment]
I think I find a bug!!!!

| Index | SentenceID | Token | Lemma |
| --- | --- | --- | --- |
| 80352 | 4901 | have | have |
| 80353 | 4901 | a | a |
| 80354 | 4901 | purpose | purpose |
| 80355 | **4901** | **. . .** | **.** |
| 80356 | **4901** | True | **.** |
| 80357 | **4901** | , | **.** |
| 80358 | 4901 | I | true |
| 80359 | 4901 | was | , |
| 80360 | 4901 | not | i |
| 80361 | 4901 | absolutely | be |
| 80362 | 4901 | certain | not |

**Comment by PavelNovichkov** [comment]
Could you please check if the bug is still present when you use tokenizer='nltk' instead of 'corenlp'?

**Comment by frayalisia** [comment]
Ok. I'll check it
