### ISSUE TITLE
Implement extractors

### ISSUE THREAD

**Issue by PavelNovichkov** [frayalisia/novelgraphs#28]
Extractors to implement:
- [x] TokenDistance
- [x] SentenceDistance
- [x] Dialog
- [x] SEquence
- [x] Dependencies

**Comment by frayalisia** [comment]
Что ты имеешь в виду под "Диалог"? только диалог или не_диалог + диалог?

**Comment by PavelNovichkov** [comment]
I think that whole text chunk (both quoted and unquoted speech together) would be fine

**Comment by frayalisia** [comment]
i'll push them after some tests

**Comment by frayalisia** [comment]
SentenceDistance как TokenDist
