### ISSUE TITLE
Add CoreNLP QuoteAnnotator

### ISSUE THREAD

**Issue by PavelNovichkov** [frayalisia/novelgraphs#3]
QuoteAnnotator is implemented in Stanford CoreNLP edu.stanford.nlp.pipeline.QuoteAnnotator class. We need to add its tags to our CoreNLP annotator, or understand how it works and reimplement it in Python.

**Comment by PavelNovichkov** [comment]
Class source at github https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/QuoteAnnotator.java

**Comment by frayalisia** [comment]
As I understand from code:
- they work with right-left quotation marks
- they have some rules about single marks in the text

_Did I miss something?_

**Comment by PavelNovichkov** [comment]
Yes, they have several non-trivial rules and consider many cases. I am going to write a short Java program to extract this annotation so that we can estimate its quality. It turns out that JSON output is not lossless, and it is impossible to add quote annotations to output JSON (without hacking JSONOutputter class).

**Comment by frayalisia** [comment]
The main problem of the day is equal double marks like "this".

**Comment by PavelNovichkov** [comment]
They claim they are able to handle it (and even more complex cases like "'Gadzooks' is what he said to me").

**Comment by frayalisia** [comment]
Hope so.
Because it's terrible problem at the time.

**Comment by frayalisia** [comment]
[Some results](https://github.com/frayalisia/novelgraphs/wiki/1-st-person) are rather strange...

**Comment by PavelNovichkov** [comment]
Added annotator `ng.annotators.Quote()` which provides `QuotationID` field.

**Comment by PavelNovichkov** [comment]
Two parameters should be added:
- [ ] `single_quotes` indicating whether or not to consider ' tokens to be quotation marks
- [ ] `max_length` - maximum character length of quotes to consider
